#!/bin/bash -e
set -x

# Get cloud-init
sudo apt update
sudo debconf-set-selections -v <<<"cloud-init cloud-init/datasources multiselect NoCloud, None" 2>/dev/null
sudo apt install -y cloud-init
#sudo debconf-set-selections -v <<<"cloud-init cloud-init/datasources multiselect NoCloud, None" 2>/dev/null; sudo dpkg-reconfigure cloud-init -f noninteractive 2>/dev/null;

# Prepare datasource
sudo tee /etc/cloud/cloud.cfg <<'YAML'
#cloud-config
# The top level settings are used as module
# and system configuration.
datasource_list: [ "NoCloud", "None"]
datasource:
  NoCloud:
    seedfrom: /boot/

# A set of users which may be applied and/or used by various modules
# when a 'default' entry is found it will reference the 'default_user'
# from the distro configuration specified below
users:
   - default

# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the above $user (debian)
disable_root: true

# This will cause the set+update hostname module to not operate (if true)
preserve_hostname: false

# Example datasource config
# datasource:
#    Ec2:
#      metadata_urls: [ 'blah.com' ]
#      timeout: 5 # (defaults to 50 seconds)
#      max_wait: 10 # (defaults to 120 seconds)

# The modules that run in the 'init' stage
cloud_init_modules:
 - migrator
 - bootcmd
 - write-files
 - mounts
 - rsyslog
 - users-groups
 #- ssh

# The modules that run in the 'config' stage
cloud_config_modules:
# Emit the cloud config ready event
# this can be used by upstart jobs for 'start on cloud-config'.
 - ssh-import-id
 - locale
 - set-passwords
 - ntp
 - timezone
 - runcmd

# The modules that run in the 'final' stage
cloud_final_modules:
 - package-update-upgrade-install
 - scripts-vendor
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - phone-home
 - final-message

# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
   # This will affect which distro class gets used
   distro: debian
   # Default user name + that default users groups (if added/used)
   default_user:
     name: pi
     #lock_passwd: True
   # Other config here will be given to the distro class and/or path classes
   paths:
      cloud_dir: /var/lib/cloud/
      templates_dir: /etc/cloud/templates/
YAML

# Create meta-data
sudo tee /boot/meta-data <<'YAML'
instance-id: iid-raspberrypi-nocloud
network-interfaces: |
  iface eth0 inet static
  address 10.0.0.1
  network 10.0.0.0
  netmask 255.255.255.0
  broadcast 10.0.0.0
  gateway 10.0.0.1
YAML

# Create user-data
sudo tee /boot/user-data <<'YAML'
#cloud-config
packages:
 - vim
 - python3-pip
 users:
  - default
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDYfQSKsP7wLLIRhOVfVwyPX7HGmorYCJCL0aANiyf5xY2GMf6G7Rro2/nqoVRUW+Phl6NEO6TWrsiy36YRcfu/V4BhTb2NHkPhEDekAsy+8ySAYp1nGIUMytgsxqI6mVX9lkb5p+62+UP0PDl0+reAPykOj7e0FDfAtXjatDv/kwE57B9YvymCuh10vTsg342pvRLjURoO1FeLGzlhD7wq3kUAkxnztvdu+MxLh2N0bCstUKWUwBuAv6aF2/hFUqkEZsaNM2q21lUlsXQss/W1l7358Evfpg1Bhm7fS1vgTqnu5EYRIdyOZyH05XzYhQPBwkTwKfueUBs+Ol+7uaK76oVoACNSMHIGPxQ06TaYakqVhllQjmaKKzH8EVNybXLkpjSsW+sp8muYdItTNvAMbmh+YkcyCXHqYzS2hGtQKnzRuROn2EfTdQgf0/YlHITW1BrMppLZVpMIqoaEh2fbNRpEhXivSoDoSiRR14LEscxM8xOLBQUWGRLj3YuXQss=
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCkcoQrSrN0B2MzmlyDrj3Oa52ABJ4Ku8VlSWh8G5PMSb1ZUGmGWyV2f52FUHtAVCpLnvrAGgTcxmy1OqT10G+tpalmvEc31T02aa3UfcWyL/OwCU7FVphCq2PIycOMSv3iFQrtO1ydujq8lozRZp8WzJg9IpKY6CTM0VWPXpKVzBAy1AoJqcKcLGpe7xKtQGbr+ywyebHT2Ulf7kf4qbL25xgBLslEd5m5olqMiH09Ik/QukoaQpfKZ0G3735tmihOwSY2qeXGrELlhdZZWf0GICB+mvVcmAeLXqihxHK8kyp08307qQvPfLCMyWJiCqxoF+5dXxvjVFytf8d2zQwb
 - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAwS/pnb7Dh0vWWZiBc4tqLxl64/0FnpUWXPDihn+whEAyb11IhKZzT7YkGj5CzXEtOPwPx/Z663DgbNkEri/h2+V97+8gp+bPZCm0uIbbiky2VO2JClquERmvlO4OQkD8JJ+soggpM32Wb4PiMTm3Rrt8R7vwJKofd5i9HpVNHgnKRKvHjCaaCCVoHPIeih+blz2tBS0T5+3G5Y7KVvcvt4KsfjWTqgYAWxaKLl9ixPkliEjpMvYxt74yORpOiaq1OBD10l2F2oCzEKehR9RbbPKy3WaCBcHFXCFj9WeJ3UDszxGIWkRQOZkS26NmmP2RW6wYmw2gyGLWxc+kBqOv

YAML

# Initialize cloud-init
sudo cloud-init init --local

# Create a script to run per boot
sudo tee /var/lib/cloud/scripts/per-boot/00_run-parts.sh <<'BASH'
#!/bin/bash

# Prevent *.sh from returning itself if there are no matches
shopt -s nullglob

# Run every per-once script
run-parts --regex '.*\.sh$' /boot/per-once

# Rename every per-once script
for f in /boot/per-once/*.sh; do
    mv $f $(dirname $f)/$(basename $f .sh).$(date +%F@%H.%M.%S)
done

# Run every per-boot script
run-parts --regex '.*\.sh$' /boot/per-boot
BASH
sudo chmod +x /var/lib/cloud/scripts/per-boot/00_run-parts.sh

# Create sample per-boot and per-once scripts
sudo mkdir -p /boot/{per-boot,per-once}
sudo tee /boot/per-boot/01_get_ready.sh \
         /boot/per-boot/02_do_it.sh \
         /boot/per-once/01_prepare.sh \
         /boot/per-once/02_install_stuff.sh <<'BASH'
#!/bin/bash

date="$(date +"%x %X")"
script_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
script_name="$(basename ${BASH_SOURCE[0]} .sh)"
log_name="$(basename $script_path)"

echo "$date - $script_name" >> /home/pi/${log_name}.out
BASH

echo "Cloud-Init setup is complete."
# vim: et sw=4 ts=4 sts=4 syntax=sh
