---
# Need to create new users before we can delete the default user
- hosts: all
  gather_facts: yes
  become: yes
  # Run initial create users with the default pi user/password
  vars:
    ansible_user: pi
    ansible_password: raspberry
  vars_files:
    - vars/utils.yml
  roles:
    - role: create_users
      ignore_errors: yes
  tasks:
    - reboot:

# Now that we're no longer using the default user with ansible we can disable it.
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    ansible_user: rbernau
  vars_files:
    - vars/utils.yml
  roles:
    - role: disable_default_user
    - role: boot_config
  tasks:
    - reboot:
