---
- name: Install isc-dhcp-server
  package:
    name: isc-dhcp-server
    state: present

- name: Setup eth0 interface with static ip
  template:
    src: "eth0.j2"
    dest: "/etc/network/interfaces.d/eth0"
    owner: root
    group: root
    mode: 600
  notify: reboot
    
- name: Disable dhcpcd for eth0
  template:
    src: "dhcpcd.conf.j2"
    dest: "/etc/dhcpcd.conf"
    owner: root
    group: root
    mode: 600
  notify: reboot
- name: Copy dhcpd.conf file
  template:
    src: "dhcpd.conf.j2"
    dest: "/etc/dhcp/dhcpd.conf"
    owner: root
    group: root
    mode: 600
  notify: reboot
- name: Use eth0 for DHCP server
  replace:
    path: /etc/default/isc-dhcp-server
    regexp: 'INTERFACESv4=""'
    replace: 'INTERFACESv4="eth0"'
  notify: reboot
