---
- name: install the latest version of bind9
  package:
    name:
      - bind9
      - bind9utils
      - dnsutils
    state: latest
  notify: 
    - reboot

- name: Copy named.conf.options file
  template:
    src: "named.conf.options.j2"
    dest: "/etc/bind/named.conf.options"
    owner: root
    group: root
    mode: 644
  notify: 
    - reboot

- name: Copy named.conf.options file
  template:
    src: "named.conf.local.j2"
    dest: "/etc/bind/named.conf.local"
    owner: root
    group: root
    mode: 644
  notify:
    - reboot

- name: Template /etc/dhcpcd.conf (option domain-name-servers)
  template:
    src: "dhcpcd.conf.j2"
    dest: "/etc/dhcpcd.conf"
    owner: root
    group: root
    mode: 600
  notify: 
    - reboot
