name: Build Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: main
    - uses: actions/checkout@v3
      with:
        path: pi-gen
        repository: RPi-Distro/pi-gen
    - name: build image
      run: ./main/wrapper_build.sh
