name: Build Image
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: main
    - uses: actions/checkout@v3
      with:
        path: pi-gen
        repository: RPi-Distro/pi-gen
    - name: build image
      run: ./main/wrapper_build.sh
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
        with:
          name: img
          path: /pi-gen/deploy/*
          retention-days: 5
